### ISSUE TITLE
No Retry limit

### ISSUE THREAD

**Issue by macdja38** [macdja38/stream-resume#1]

**Comment by itslukej** [comment]
🤔

**Comment by macdja38** [comment]
Partially fixed in https://github.com/macdja38/stream-resume/commit/1d3f2b67b4d771ec43c7059e7ef48edc6b37887e
Properly forwards errors instead of simply ending in https://github.com/macdja38/stream-resume/commit/68efd3ba53dd4e1b7209ed2cc001411b6f412141
